site_name: NegKit
site_url: https://manuales.algoritmia.sv/negkit/
site_description: Manual de usuario de NegKit
site_author: Edwin Fajardo
copyright: Copyright &copy;2024 Algoritmia SV
site_dir: /store/bphp/manuals/negkit
nav:
  - Inicio: index.md
  - Ventas:
    - Ventas: ventas/ventas.md
    - Clientes: ventas/clientes.md
    - Créditos: ventas/creditos.md
  - Compras:
    - Compras: compras/compras.md
    - Proveedores: compras/proveedores.md
    - 'Inventario inicial': compras/inventario-inicial.md
  - Catálogo:
    - Productos: catalogo/productos.md
    - Servicios: catalogo/servicios.md
    - Categorías: catalogo/categorias.md
    - Combos: catalogo/combos.md
    - 'Productos genéricos': catalogo/productos-genericos.md
    - 'Unidades de medida': catalogo/unidades-de-medida.md
  - Reportes:
    - 'Reportes de ventas': reportes/reportes-ventas.md
    - 'Reportes de compras': reportes/reportes-compras.md
    - 'Reportes de utilidad': reportes/reportes-utilidad.md
    - Inventerio: reportes/reportes-inventario.md
    - Kardex: reportes/kardex.md
    - Precederos: reportes/perecederos.md
    - 'Productos en escasez': reportes/escasez.md
    - 'Productos en exceso': reportes/exceso.md
  - Herramientas:
    - 'Historial de actividades': herramientas/historial-actividades.md
    - 'Papelera de reciclaje': herramientas/papelera.md
  - Configuraciones:
    - 'Datos de la empresa': configuraciones/entidad.md
    - Preferencias: configuraciones/preferencias.md
    - Roles: configuraciones/roles.md
    - Usuarios: configuraciones/usuarios.md
    - Numeraciones: configuraciones/numeraciones.md
theme:
  name: mkdocs
  nav_style: dark
  locale: es
extra_css:
  - css/algoritmiasv.css
